import re

class ResponseFormatter:
    @staticmethod
    def format_response(response: str, top_chunks: list) -> str:
        """
        Parses and formats the response from the LLM.
        Enforces 3-sentence limit and citation format.
        """
        if "I don't have this information in my current sources" in response or \
           "I'm designed to provide only factual information" in response or \
           "Error:" in response:
            return response
            
        # Remove any citations generated by the LLM
        main_text = re.sub(r'(?i)\n*Source:\s*.*', '', response)
        main_text = re.sub(r'(?i)\n*Last updated from sources:\s*.*', '', main_text)
        main_text = main_text.strip()

        if not main_text:
            return "I don't have this information in my current sources. Please check the official HDFC MF website."
        
        # Enforce 3 sentences (split by .!? followed by whitespace)
        sentences = re.split(r'(?<=[.!?])\s+', main_text)
        if len(sentences) > 3:
            main_text = " ".join(sentences[:3])
            
        # Extract metadata from top chunks if LLM failed to include it properly
        url = "Unknown"
        date = "Unknown"
        if top_chunks and len(top_chunks) > 0:
            # Assume top_chunks contains Document objects or dicts
            best_chunk = top_chunks[0]
            if hasattr(best_chunk, 'metadata'):
                url = best_chunk.metadata.get('source_url', 'Unknown')
                date = best_chunk.metadata.get('last_updated', 'Unknown')
            elif isinstance(best_chunk, dict) and 'metadata' in best_chunk:
                url = best_chunk['metadata'].get('source_url', 'Unknown')
                date = best_chunk['metadata'].get('last_updated', 'Unknown')
            
        # Build the final response
        final_response = main_text.strip()
        final_response += f"\n\nSource: {url}"
        final_response += f"\nLast updated from sources: {date}"
        
        return final_response
