"""
ingestion/preprocessor.py
-------------------------
Task 1.3 — Preprocessing

Responsible for text cleaning and metadata extraction standardization.
It accepts document dicts from loaders (like loader.py), applies general text
cleaning (removing excessive whitespace, standardizing newlines), extracts
and validates the metadata schema, and persists the processed documents to 
`data/processed/` in a structured JSON format ready for chunking.

Key operations:
- Standardize metadata (`source_url`, `document_type`, `scheme_name`,
  `publisher`, `last_updated`).
- Normalize text (condense multiple newlines, strip trailing spaces), while
  leaving Markdown tables intact.
- Save to `data/processed/<slug>.json`.
"""

import json
import logging
import re
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

from config import PROCESSED_DATA_DIR

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s — %(message)s",
)
logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Preprocessing Logic
# ---------------------------------------------------------------------------

def _clean_text(text: str) -> str:
    """
    Apply generic text cleaning to the full text.
    - Condenses 3+ consecutive newlines to exactly 2 newlines (paragraph break).
    - Removes trailing spaces on each line.
    - Does NOT modify markdown tables (newlines and pipes are preserved).
    """
    # Remove trailing spaces
    lines = [line.rstrip() for line in text.split("\n")]
    cleaned = "\n".join(lines)
    
    # Condense 3+ newlines to 2
    cleaned = re.sub(r"\n{3,}", "\n\n", cleaned)
    
    return cleaned.strip()

def preprocess_document(doc: dict[str, Any]) -> dict[str, Any]:
    """
    Validates metadata and cleans text for a loaded document.
    
    Args:
        doc: A document dictionary generated by a loader.
        
    Returns:
        A cleaned and structured dictionary ready for chunking and persistence.
    """
    if doc.get("status") != "success":
        logger.warning(f"Skipping failed document: {doc.get('source_url', 'Unknown')}")
        return doc
        
    # Standardize Metadata schema
    metadata = {
        "source_url": doc.get("source_url", ""),
        "document_type": doc.get("document_type", "unknown"),
        "scheme_name": doc.get("scheme_name", ""),
        "publisher": doc.get("publisher", ""),
        "last_updated": doc.get("last_updated", ""),
        "title": doc.get("title", ""),
    }
    
    # Clean full text
    raw_text = doc.get("full_text", "")
    cleaned_text = _clean_text(raw_text)
    
    processed_doc = {
        "text": cleaned_text,
        "metadata": metadata,
        # Keep sections/tables for advanced chunking if needed later
        "sections": doc.get("sections", {}),
        "tables": doc.get("tables", []),
        "status": "success",
    }
    
    return processed_doc

def save_processed_document(processed_doc: dict[str, Any], output_dir: str = PROCESSED_DATA_DIR) -> str:
    """
    Persist the processed document as a JSON file in the processed directory.
    
    Args:
        processed_doc: The cleaned document dictionary.
        output_dir: Directory to save the file in.
        
    Returns:
        Path to the saved JSON file.
    """
    out_path = Path(output_dir)
    out_path.mkdir(parents=True, exist_ok=True)
    
    url = processed_doc["metadata"]["source_url"]
    slug = urlparse(url).path.strip("/").replace("/", "_")
    if not slug:
        # Fallback slug if url parsing is weird
        slug = processed_doc["metadata"]["scheme_name"].lower().replace(" ", "_")
        
    file_path = out_path / f"{slug}_processed.json"
    
    with file_path.open("w", encoding="utf-8") as f:
        json.dump(processed_doc, f, indent=2, ensure_ascii=False)
        
    return str(file_path.resolve())

def process_and_save_all(loaded_docs: list[dict[str, Any]]) -> list[str]:
    """
    Preprocess and persist a batch of loaded documents.
    
    Args:
        loaded_docs: List of document dicts from loaders.
        
    Returns:
        List of paths to the saved processed JSON files.
    """
    saved_paths = []
    success_count = 0
    
    for doc in loaded_docs:
        if doc.get("status") == "success":
            processed = preprocess_document(doc)
            path = save_processed_document(processed)
            saved_paths.append(path)
            success_count += 1
            
    logger.info(f"Preprocessing complete: {success_count}/{len(loaded_docs)} documents successfully processed and saved.")
    return saved_paths

# ---------------------------------------------------------------------------
# CLI entry point for manual testing
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import sys
    from ingestion.loader import load_all_from_manifest
    
    logger.info("Loading documents from manifest...")
    docs = load_all_from_manifest()
    
    logger.info("Preprocessing and saving documents...")
    saved_files = process_and_save_all(docs)
    
    for f in saved_files:
        print(f"[OK] Saved processed document: {f}")
        
    sys.exit(0 if len(saved_files) == len([d for d in docs if d["status"] == "success"]) else 1)
